os: 
  - Visual Studio 2017
  
branches:
  only:
  - master

platform:
  - x64

configuration:
  - Release
  #- Debug

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
    - generator: "Visual Studio 15"
    - generator: "Visual Studio 13"

matrix:
  fast_finish: true

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - set BOOST_DIR=C:/Libraries/boost_1_64_0

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - >
    cmake ..
    -G "%generator%" 
    -DBUILD_TESTS=ON
    -DSVBB_BUILD_EXAMPLES=ON
    -DBOOST_ROOT=%BOOST_DIR%
  - cmake --build . --target ALL_BUILD --config %configuration% 

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%/build
  - ctest -C %configuration% --output-on-failure .